"""add document_name to api_documents

Revision ID: 844b341d583b
Revises: d6415eb07feb
Create Date: 2025-12-15 16:11:26.597350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '844b341d583b'
down_revision = 'd6415eb07feb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_shipment_id'), 'audit_logs', ['shipment_id'], unique=False)
    op.create_table('certificates_of_origin',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('exporter_name', sa.String(length=255), nullable=True),
    sa.Column('exporter_address', sa.Text(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_of_origin_shipment_id'), 'certificates_of_origin', ['shipment_id'], unique=False)
    op.create_table('freight_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_period_start', sa.Date(), nullable=True),
    sa.Column('contract_period_end', sa.Date(), nullable=True),
    sa.Column('base_freight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bunker_adjustment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_freight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transport_mode', sa.String(length=20), nullable=True),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_documents_shipment_id'), 'freight_documents', ['shipment_id'], unique=False)
    op.create_table('packing_lists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('packing_list_number', sa.String(length=100), nullable=True),
    sa.Column('packing_date', sa.Date(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('shipper_name', sa.String(length=255), nullable=True),
    sa.Column('total_packages', sa.Integer(), nullable=True),
    sa.Column('total_gross_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_net_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=False),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_lists_shipment_id'), 'packing_lists', ['shipment_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('passed_checks', sa.Integer(), nullable=True),
    sa.Column('failed_checks', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_shipment_id'), 'validation_results', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    op.create_table('boe_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('boe_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boe_id'], ['bill_of_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boe_items_boe_id'), 'boe_items', ['boe_id'], unique=False)
    op.create_index(op.f('ix_boe_items_hs_code'), 'boe_items', ['hs_code'], unique=False)
    op.create_table('coo_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('coo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coo_id'], ['certificates_of_origin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coo_items_coo_id'), 'coo_items', ['coo_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_hs_code'), 'invoice_items', ['hs_code'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('packing_list_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('packing_list_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('package_number', sa.String(length=50), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_list_items_packing_list_id'), 'packing_list_items', ['packing_list_id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('validation_result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=50), nullable=True),
    sa.Column('target_document', sa.String(length=50), nullable=True),
    sa.Column('correction_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_severity'), 'validation_errors', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_errors_validation_result_id'), 'validation_errors', ['validation_result_id'], unique=False)
    op.alter_column('api_documents', 'extraction_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('api_documents_document_id_key'), 'api_documents', type_='unique')
    op.drop_index(op.f('idx_api_documents_created_at'), table_name='api_documents')
    op.drop_index(op.f('idx_api_documents_document_id'), table_name='api_documents')
    op.drop_index(op.f('idx_api_documents_document_type'), table_name='api_documents')
    op.drop_index(op.f('idx_api_documents_extraction_status'), table_name='api_documents')
    op.drop_index(op.f('idx_api_documents_shipment_id'), table_name='api_documents')
    op.create_index(op.f('ix_api_documents_document_id'), 'api_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_api_documents_document_type'), 'api_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_api_documents_extraction_status'), 'api_documents', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_api_documents_shipment_id'), 'api_documents', ['shipment_id'], unique=False)
    op.drop_table_comment(
        'api_documents',
        existing_comment='API document metadata storage - replaces in-memory dict for scalability',
        schema=None
    )
    op.add_column('bill_of_entries', sa.Column('declaration_number', sa.String(length=100), nullable=False))
    op.add_column('bill_of_entries', sa.Column('declaration_date', sa.Date(), nullable=True))
    op.add_column('bill_of_entries', sa.Column('consignee_name', sa.String(length=255), nullable=True))
    op.add_column('bill_of_entries', sa.Column('consignee_address', sa.Text(), nullable=True))
    op.add_column('bill_of_entries', sa.Column('shipper_name', sa.String(length=255), nullable=True))
    op.add_column('bill_of_entries', sa.Column('shipper_address', sa.Text(), nullable=True))
    op.add_column('bill_of_entries', sa.Column('fob_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bill_of_entries', sa.Column('freight_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bill_of_entries', sa.Column('insurance_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bill_of_entries', sa.Column('cif_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bill_of_entries', sa.Column('duty_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bill_of_entries', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('bill_of_entries', sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('bill_of_entries', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bill_of_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bill_of_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('bill_of_entries_boe_number_key'), 'bill_of_entries', type_='unique')
    op.create_index(op.f('ix_bill_of_entries_declaration_number'), 'bill_of_entries', ['declaration_number'], unique=True)
    op.create_index(op.f('ix_bill_of_entries_document_id'), 'bill_of_entries', ['document_id'], unique=False)
    op.create_index(op.f('ix_bill_of_entries_shipment_id'), 'bill_of_entries', ['shipment_id'], unique=False)
    op.drop_column('bill_of_entries', 'boe_date')
    op.drop_column('bill_of_entries', 'importer_name')
    op.drop_column('bill_of_entries', 'importer_address')
    op.drop_column('bill_of_entries', 'boe_number')
    op.alter_column('document_pages', 'extraction_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('invoices', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_shipment_id'), 'invoices', ['shipment_id'], unique=False)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('shipments_shipment_number_key'), 'shipments', type_='unique')
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.create_unique_constraint(op.f('shipments_shipment_number_key'), 'shipments', ['shipment_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_invoices_shipment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('invoices', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('document_pages', 'extraction_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('bill_of_entries', sa.Column('boe_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('bill_of_entries', sa.Column('importer_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bill_of_entries', sa.Column('importer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('bill_of_entries', sa.Column('boe_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bill_of_entries_shipment_id'), table_name='bill_of_entries')
    op.drop_index(op.f('ix_bill_of_entries_document_id'), table_name='bill_of_entries')
    op.drop_index(op.f('ix_bill_of_entries_declaration_number'), table_name='bill_of_entries')
    op.create_unique_constraint(op.f('bill_of_entries_boe_number_key'), 'bill_of_entries', ['boe_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('bill_of_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bill_of_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bill_of_entries', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('bill_of_entries', 'raw_parsed_data')
    op.drop_column('bill_of_entries', 'currency')
    op.drop_column('bill_of_entries', 'duty_value')
    op.drop_column('bill_of_entries', 'cif_value')
    op.drop_column('bill_of_entries', 'insurance_value')
    op.drop_column('bill_of_entries', 'freight_value')
    op.drop_column('bill_of_entries', 'fob_value')
    op.drop_column('bill_of_entries', 'shipper_address')
    op.drop_column('bill_of_entries', 'shipper_name')
    op.drop_column('bill_of_entries', 'consignee_address')
    op.drop_column('bill_of_entries', 'consignee_name')
    op.drop_column('bill_of_entries', 'declaration_date')
    op.drop_column('bill_of_entries', 'declaration_number')
    op.create_table_comment(
        'api_documents',
        'API document metadata storage - replaces in-memory dict for scalability',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_api_documents_shipment_id'), table_name='api_documents')
    op.drop_index(op.f('ix_api_documents_extraction_status'), table_name='api_documents')
    op.drop_index(op.f('ix_api_documents_document_type'), table_name='api_documents')
    op.drop_index(op.f('ix_api_documents_document_id'), table_name='api_documents')
    op.create_index(op.f('idx_api_documents_shipment_id'), 'api_documents', ['shipment_id'], unique=False)
    op.create_index(op.f('idx_api_documents_extraction_status'), 'api_documents', ['extraction_status'], unique=False)
    op.create_index(op.f('idx_api_documents_document_type'), 'api_documents', ['document_type'], unique=False)
    op.create_index(op.f('idx_api_documents_document_id'), 'api_documents', ['document_id'], unique=False)
    op.create_index(op.f('idx_api_documents_created_at'), 'api_documents', [sa.literal_column('created_at DESC')], unique=False)
    op.create_unique_constraint(op.f('api_documents_document_id_key'), 'api_documents', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_documents', 'extraction_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_validation_errors_validation_result_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_severity'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_packing_list_items_packing_list_id'), table_name='packing_list_items')
    op.drop_table('packing_list_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_hs_code'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_coo_items_coo_id'), table_name='coo_items')
    op.drop_table('coo_items')
    op.drop_index(op.f('ix_boe_items_hs_code'), table_name='boe_items')
    op.drop_index(op.f('ix_boe_items_boe_id'), table_name='boe_items')
    op.drop_table('boe_items')
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_shipment_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_packing_lists_shipment_id'), table_name='packing_lists')
    op.drop_table('packing_lists')
    op.drop_index(op.f('ix_freight_documents_shipment_id'), table_name='freight_documents')
    op.drop_table('freight_documents')
    op.drop_index(op.f('ix_certificates_of_origin_shipment_id'), table_name='certificates_of_origin')
    op.drop_table('certificates_of_origin')
    op.drop_index(op.f('ix_audit_logs_shipment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
