"""add_document_pages_table

Revision ID: d6415eb07feb
Revises: 252629112b2a
Create Date: 2025-12-15 13:13:35.971876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6415eb07feb'
down_revision = '252629112b2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'document_pages',
        sa.Column('page_id', sa.String(length=36), nullable=False),
        sa.Column('document_id', sa.String(length=36), nullable=False),
        sa.Column('page_number', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=512), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_size', sa.BigInteger(), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('extraction_status', sa.String(length=50), nullable=True, server_default='pending'),
        sa.Column('extraction_result', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('page_id'),
        sa.ForeignKeyConstraint(['document_id'], ['api_documents.document_id'], ondelete='CASCADE'),
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_page_number'), 'document_pages', ['page_number'], unique=False)
    
    # Add is_multi_page flag to api_documents table
    op.add_column('api_documents', sa.Column('is_multi_page', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('api_documents', sa.Column('total_pages', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_documents', 'total_pages')
    op.drop_column('api_documents', 'is_multi_page')
    op.drop_index(op.f('ix_document_pages_page_number'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    # ### end Alembic commands ###
