"""initial migration - all tables

Revision ID: 697b41a5d33b
Revises: 
Create Date: 2025-11-11 09:49:18.630439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '697b41a5d33b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('transport_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_shipment_id'), 'audit_logs', ['shipment_id'], unique=False)
    op.create_table('bill_of_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('declaration_number', sa.String(length=100), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('shipper_name', sa.String(length=255), nullable=True),
    sa.Column('shipper_address', sa.Text(), nullable=True),
    sa.Column('fob_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('freight_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('insurance_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cif_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('duty_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_of_entries_declaration_number'), 'bill_of_entries', ['declaration_number'], unique=True)
    op.create_index(op.f('ix_bill_of_entries_shipment_id'), 'bill_of_entries', ['shipment_id'], unique=False)
    op.create_table('certificates_of_origin',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('exporter_name', sa.String(length=255), nullable=True),
    sa.Column('exporter_address', sa.Text(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_of_origin_shipment_id'), 'certificates_of_origin', ['shipment_id'], unique=False)
    op.create_table('freight_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_period_start', sa.Date(), nullable=True),
    sa.Column('contract_period_end', sa.Date(), nullable=True),
    sa.Column('base_freight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bunker_adjustment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_freight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transport_mode', sa.String(length=20), nullable=True),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_documents_shipment_id'), 'freight_documents', ['shipment_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('shipper_name', sa.String(length=255), nullable=True),
    sa.Column('shipper_address', sa.Text(), nullable=True),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_fob_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('freight_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('insurance_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_invoice_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_shipment_id'), 'invoices', ['shipment_id'], unique=False)
    op.create_table('packing_lists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('packing_list_number', sa.String(length=100), nullable=True),
    sa.Column('packing_date', sa.Date(), nullable=True),
    sa.Column('consignee_name', sa.String(length=255), nullable=True),
    sa.Column('shipper_name', sa.String(length=255), nullable=True),
    sa.Column('total_packages', sa.Integer(), nullable=True),
    sa.Column('total_gross_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_net_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=False),
    sa.Column('raw_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_lists_shipment_id'), 'packing_lists', ['shipment_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('passed_checks', sa.Integer(), nullable=True),
    sa.Column('failed_checks', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_shipment_id'), 'validation_results', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    op.create_table('boe_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('boe_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boe_id'], ['bill_of_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boe_items_boe_id'), 'boe_items', ['boe_id'], unique=False)
    op.create_index(op.f('ix_boe_items_hs_code'), 'boe_items', ['hs_code'], unique=False)
    op.create_table('coo_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('coo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coo_id'], ['certificates_of_origin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coo_items_coo_id'), 'coo_items', ['coo_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_hs_code'), 'invoice_items', ['hs_code'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('packing_list_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('packing_list_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('package_number', sa.String(length=50), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_list_items_packing_list_id'), 'packing_list_items', ['packing_list_id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('validation_result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=50), nullable=True),
    sa.Column('target_document', sa.String(length=50), nullable=True),
    sa.Column('correction_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_severity'), 'validation_errors', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_errors_validation_result_id'), 'validation_errors', ['validation_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_errors_validation_result_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_severity'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_packing_list_items_packing_list_id'), table_name='packing_list_items')
    op.drop_table('packing_list_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_hs_code'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_coo_items_coo_id'), table_name='coo_items')
    op.drop_table('coo_items')
    op.drop_index(op.f('ix_boe_items_hs_code'), table_name='boe_items')
    op.drop_index(op.f('ix_boe_items_boe_id'), table_name='boe_items')
    op.drop_table('boe_items')
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_shipment_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_packing_lists_shipment_id'), table_name='packing_lists')
    op.drop_table('packing_lists')
    op.drop_index(op.f('ix_invoices_shipment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_freight_documents_shipment_id'), table_name='freight_documents')
    op.drop_table('freight_documents')
    op.drop_index(op.f('ix_certificates_of_origin_shipment_id'), table_name='certificates_of_origin')
    op.drop_table('certificates_of_origin')
    op.drop_index(op.f('ix_bill_of_entries_shipment_id'), table_name='bill_of_entries')
    op.drop_index(op.f('ix_bill_of_entries_declaration_number'), table_name='bill_of_entries')
    op.drop_table('bill_of_entries')
    op.drop_index(op.f('ix_audit_logs_shipment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
